### PR TITLE
Typescript declarations

### PR DESCRIPTION
**Pull request by alexkharech**

### CODE REVIEW

**Comment by alexkharech** [comment]
This will add full support for type declarations.

**Comment by jkempff** [comment]
Thanks for your contribution, I'll publish the next version shortly after merging your pull request.

**Comment by 810505339** [comment]
How use?

**Comment by alexkharech** [comment]
image

typed RouterLink:
image

typed element: 
image

with props
image
image

**Comment by 810505339** [comment]
Typescript  
image

**Comment by 810505339** [comment]
image

**Comment by alexkharech** [comment]
hmm,  yes, there is a conflict with the `color` parameter, strange behavior
change param name please, this bug

image

image

**Comment by 810505339** [comment]
image
Why is this?

**Comment by alexkharech** [comment]
you have not completed the method and are trying to return a string or undefined value as a string

**Comment by alexkharech** [comment]
function with a parameter should return a string

**Comment by alexkharech** [comment]
from vue docs
`{
type: String,
required: true
}`

**Comment by alexkharech** [comment]
types are taken from official vue types

**Comment by alexkharech** [comment]
from vue docs with custom types 
image

**Comment by 810505339** [comment]
image
image
image

hmm   type error  run normal

**Comment by alexkharech** [comment]
```ts
// from vue docs
{type: String} // string | undefined
{type:String, required: true } // string

// use
{type:String, required: true }
// or
`${p => p.colots || ''} // to string`

```

**Comment by 810505339** [comment]
````js

`${p => p.colots || ''} // success`

 //
{type:String, required: true }  //error

**Comment by alexkharech** [comment]
with default
image

I take the types completely immutable from `ExtractPropTypes`, obviously vue wants default values

**Comment by alexkharech** [comment]
otherwise there is no certainty that the string will be passed

**Comment by 810505339** [comment]
Thank you !

**Pull request merged**
